---
title: "NLP"
description: |

---

*This page lists some useful resources for students and researchers interested in text-as-data*

#### **Corpus**

**[Norwegian Colossal Corpus][NCC]**

- Collection of multiple Norwegian corpuses that are suitable for training large language models or conducting independent research. The corpus contains government reports, *Stortingsforhandlingene*, *Evalueringsrapporter*, laws and *NOUs*, online newspapers, Wikipedia, and out-of-copyrights books from the Norwegian National Library. 


**Norwegian Parliamentary Debates Dataset 1945--2024**

&nbsp; with Jon Fiva and Henning Øien, Accepted, **Nature Scientific Data** (2024) [[DATA]][NPD]

<font size="1"> Data set with all Norwegian Parliamentary speeches in the period 1945 -- 2024. We also include speaker and speech meta data (e.g., committee membership, district, minister, elected, deputy...). Can be merged with [Fiva and Smith, 2022][fivasmith] for comprehensive background data on national-level politicians.</font>


**[Norwegian NLP resources][nor_nlp]**

- List of useful Norwegian NLP resources, which covers both data/corpus and methods that supports NLP in Norwegian.


-------------

#### **Methods**

**[Intro to Quanteda][quanteda]**

- Well-documented and intuitive introduction to quantitative text analysis in R using the Quanteda package


**[Text Algorithms in Economics (Ash and Hansen, 2023)][ash_hansen]**

- Excellent overview of text algorithms in economics


**[Text as Data (Gentzkow, Kelly, and Taddy, 2019)][GKT]**

- One of the classic overviews of text-as-data in economic research

**[Multilanguage Word Embeddings for Social Scientists (Wirshing et al., 2024)][MultilanguageWB]**

- Multi-language "a la carte" word embeddings (also works in Norwegian)

-------------

#### **Other useful resources**

**[Oslo-Bergen Tagger][oslobergentagger]**

- Morphological and syntactic tagger for Norwegian. Useful for identifying grammatical morphemes and Part-Of-Speech tagging

**[Friends Don't Let Friends Make Bad Graphs][friends_graphs]**

- Some data visualization pitfalls to avoid



[NCC]: https://github.com/NbAiLab/notram/blob/master/guides/corpus_description.md
[fivasmith]: https://www.jon.fiva.no/data.htm
[quanteda]: https://tutorials.quanteda.io/
[lameducks]: https://www.jon.fiva.no/data/Fiva-Nedregard-QJPS-Replication.zip
[nor_nlp]: https://github.com/web64/norwegian-nlp-resources
[oslobergentagger]: https://tekstlab.uio.no/obt-ny/
[GKT]: https://web.stanford.edu/~gentzkow/research/text-as-data.pdf
[ash_hansen]: https://sekhansen.github.io/pdf_files/text_algos_econ.pdf
[friends_graphs]: https://github.com/cxli233/FriendsDontLetFriends
[NPD]: https://www.dropbox.com/scl/fi/nibtll2du282lx1zk982m/NPD_v1.zip?rlkey=lrjlw62mytavv4hqndr2v9bqe&st=twatcjx6&dl=0
[MultilanguageWB]: https://arthurspirling.org/documents/alce.pdf

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```
