---
title: "Research"
description: |

---


### Publications

[_Group Identities and Parliamentary Debates_][GroupIdentities] (2025)  
&nbsp; with Jon Fiva and Henning Øien, Forthcoming, **Journal of Politics**

[_Norwegian Parliamentary Debates Dataset 1945--2024_][NPD_paper]  
&nbsp; with Jon Fiva and Henning Øien, **Nature Scientific Data** (2025) [[DATA]][NPD]

<font size="1"> Data set with all Norwegian Parliamentary speeches in the period 1945 -- 2024. We also include speaker and speech meta data (e.g., committee membership, district, minister, elected, deputy...). </font> 

_Legislative party groups and party cohesion (book chapter)_  
&nbsp; with Martin Søyland, **Oxford Handbook of Norwegian Politics** (2025)

[_How Does Party Discipline Affect Legislative Behavior? Evidence from Within-Term Variation in Lame-Duck Status_][LameDucks]  
&nbsp; with Jon Fiva, **Quarterly Journal of Political Science** (2024)

[Frøyland, K., Nordberg, T. H., & Nedregård, O. (2018). Nyere kunnskap om inkluderende arbeidsliv (IA)][InkluderendeArbeidsliv]

[Nedregård, O., & Abrahamsen, B. (2018). Frafall fra profesjonsutdanningene ved OsloMet. ISO 690][Frafall]


### Working papers


_The Sound of Silence: The effect of legislative misalignment on the representation of constituency interests_  (2025) **Under Review**  
&nbsp; with Vardges Levonyan

 <font size="1"> How do elected officials respond when they learn that they are misaligned with their constituencies? While existing research has documented that politicians either update their positions or discount disagreeable public opinion, we propose and investigate a third mechanism: strategic issue avoidance. Using the 2016 Brexit referendum as an exogenous information treatment, we study how Members of Parliament (MPs) responded to sudden, measurable incongruence with their constituencies. Using a difference-in-differences framework comparing Remain-supporting MPs in Leave-voting constituencies to similarly positioned MPs in Remain-voting constituencies, we find that misaligned MPs substantially participate less in EU-related topics following the referendum. This drop in participation is not compensated by increased discussion in other topics. When they do speak about the EU, they avoid stance-taking and their language becomes less extreme. These effects are specific to the EU topic, robust to a wide range of specifications, and not driven by regional or party dynamics. The findings provide the first large-scale causal evidence of strategic issue avoidance in legislative speech and highlight important implications for studying political preferences through text. Specifically, silence may reflect strategic withdrawal rather than moderation or diminished salience, potentially introducing bias into speech-based measures of representation. Additionally, strategic issue avoidance may suppress meaningful debate on high-salience issues, thereby shaping democratic accountability and policy outcomes. </font> 


_Staying in Line or Straying for Votes: Party Discipline and Dyadic Representation_ (2025)  

<font size="1"> How does strong party discipline shape legislators' responsiveness to local concerns? In list-based proportional representation systems, parties' control of ballot rankings creates strong incentives to align with party elites, which is postulated to distort the constituency-representative link. I develop a theory of cohesion under PR and test it in Norway -- a uniquely beneficial setting to study party discipline. Leveraging seat security to capture within-party, within-district variations in incentives to align with districts, I show that legislators who are more dependent on local voters to secure reelection deviate more from the party line during local distress, compared to safe MPs. Deviations are rewarded by constituents but penalized by voters in other districts, demonstrating how deviations can benefit the legislator but be costly to the party. This refines our understanding of cohesion under PR by showing how electoral incentives shape legislative behavior not only across electoral systems but also within them. </font> 



_The female vote and PR adoption_  (2025)   
&nbsp; with Mona Morgan-Collins

 <font size="1"> Did women’s suffrage play any role in the adoption of proportional systems (PR)?
Extant literature uncovers three broad explanations for the spread of PR across Western
Europe at the turn of the 20th century. These explanations emphasize the rise of
electoral, economic and party threats generated by the expansion of men’s suffrage.
Interestingly, neither account considers the role of women’s suffrage. This ‘analytical’
invisibility of women’s suffrage is striking, especially given that countries that adopted
both PR and women’s suffrage at the turn of the 20th century almost invariably adopted
PR at the same time or shortly after women’s suffrage.
In this paper, we suggest that this sequencing of electoral reforms was not coincidental
and develop a novel explanation of PR adoption that highlights an electoral threat
posed by women’s suffrage. Women’s votes were both distinct as well as more volatile
than men’s. This required that politicians adapted their campaign appeals and built
solid support base among women. We argue that support of PR was a direct response
to the influx of new voters. Framing PR as a group-based appeal to women, politicians
could both better capture and stabilize women’s votes, mitigating the threats posed by
women’s suffrage.
Using the case of Norway, we conduct extensive archival work to demonstrate that politicians frequently justified
PR reform with references to women’s representation and that women’s groups invariably
lobbied for the reform. Using district-level electoral and roll-call data, we then
show that politicians were more likely to vote for PR in districts when women constituted
larger share of voters. Including a large battery of controls, we account for
all existing explanation and show that the weight of women’s votes is the strongest
predictor of PR than any other extant explanations.
Beyond uncovering a novel explanation of PR adoption at the turn of the 20th century,
this paper has profound implications for the role of women’s suffrage on women’s
representation. Our results suggest that women’s suffrage alone may not improve
women’s descriptive and substantive representation if it is not accompanied with an
otherwise inclusive electoral institution.  </font> 
 
	
### Work in progress


_Gendered Voices in Climate Politics: Evidence from the UK Parliament_  

 <font size="1">	Are female legislators more attentive to climate change than men? Despite evidence that female voters express greater concern for climate change and more frequently engage in pro-environmental behavior, it remains unclear whether these gender differences are mirrored in legislatures. Using a sharp regression discontinuity design in UK parliamentary elections, I compare the climate attentiveness of women who narrowly won against a man to that of men who narrowly won against a woman. Contrary to expectations based on gender differences in the electorate, I find that narrowly elected women dedicate a significantly smaller share of their term to climate topics than narrowly elected men. This suggests that, at least in the context of climate change, descriptive representation does not mechanically translate into substantive representation. </font> 


_The History of Redistributive Arguments_  
&nbsp; with Hooman Habibnia, Morten Støstad and Jeffrey Yusof

 <font size="1">Redistribution lies at the heart of democratic politics, shaping debates over who pays, who benefits, and the role of the state. Understanding how elected representatives frame redistribution across time, parties, and economic conditions is key to explaining the evolution of fiscal policy and welfare states. This paper examines 150 years of redistributive argumentation in the U.S. Congress, a setting marked by major turning points such as the New Deal, the Great Society, the Reagan era, and the Great Recession, as well as increasing partisan polarization.
We construct the first long-run, speech-level dataset of pro- and anti-redistributive arguments using the full digitized Congressional Record from 1879 to 2022. Our main measures are attentiveness, the share of speeches devoted to redistribution, and positioning, whether legislators argue for or against it. We also analyze how redistributive rhetoric varies across policy domains, over time, and between parties. </font> 

_More Catholic than the Pope? Ethnic Identity and Political Ideology_  
&nbsp; with Apurav Yash Bhatiya, Sahar Parsa, Debraj Ray and Sarah Schneider-Strawczynski

_The causal effect of trust in government on green policymaking_  

_Chilling in the Shade: Climate change resilience and climate change beliefs_  

_Is Anyone Watching? The Effect of Green Social Norms on Self-Conscious Emotions_  
&nbsp; with Vin Arceneaux and Can Zengin

_Moral Values, Folklore, and Gender-Based Violence_   
with Sevinç Bermek, Konstantinos Matakos, Asli Unan

_All You Need is Love? Romantic Ideals and Gendered Violence_   
&nbsp; with Sevinç Bermek, Konstantinos Matakos, Asli Unan


### Media

["Støres regjering er balansert på kjønn. Men hvor er distriktene og arbeiderklassen?"][arbeiderklasse_regjering], Dagens Næringsliv (2025)

["Unge forskere"][unge_forskere], Khrono (2025) 

["Snakker mer om næringer de eier aksjer i"][aksjer], Dagens Næringsliv (2023)

["Hyttepåske for hvem?"][hyttepaaske], NRK (2021)

["Må det en krise til før politikerne våkner?"][krise], Aftenposten (2020)

["Amerikanske tilstander"][amerikanske_tilstander], Dagsavisen (2019)

["Faglig interesserte studenter fullfører oftere utdanningen"][faglig_interessert], forskning.no (2018)

[arbeiderklasse_regjering]: https://www.dn.no/innlegg/politikk/mangfold/forskning/god-kjonnsbalanse-men-hvor-er-distriktene-og-arbeiderklassen/2-1-1785596?zephr_sso_ott=lYArEf

[unge_forskere]: https://www.khrono.no/hun-er-postdoktor-ved-sciences-po-tjener-mindre-enn-som-stipendiat-i-norge/943938

[NPD_paper]: https://rdcu.be/d5o0G

[NPD]: https://www.dropbox.com/scl/fi/nibtll2du282lx1zk982m/NPD_v1.zip?rlkey=lrjlw62mytavv4hqndr2v9bqe&st=twatcjx6&dl=0

[StayingInLine1]: https://www.dropbox.com/scl/fi/ciaumjg80o4bvizgt3edm/StayingInLine.pdf?rlkey=gszm2arcbbl2uu1rxidjseehv&st=jsatm1cw&dl=0

[ChillingInTheShade]: https://www.dropbox.com/scl/fi/yj2dok5qm0ntkfuv67c3g/ChillingInTheShade.pdf?rlkey=t6qceyv59xm3nymnbfdq051y6&dl=0

[aksjer]: https://www.dn.no/innlegg/politikk/investeringer/aksjer/snakker-mer-om-naringer-de-eier-aksjer-i/2-1-1519931

[SpeechIsSilver]: https://www.dropbox.com/s/7gq0t8xe68gbqlo/SpeechIsSilver.pdf?dl=0

[LameDucks]: https://www.nowpublishers.com/article/Details/QJPS-22094
[GroupIdentities]: https://www.journals.uchicago.edu/doi/10.1086/737781

[Frafall]: https://oda.oslomet.no/oda-xmlui/handle/20.500.12199/3013
[InkluderendeArbeidsliv]: https://www.regjeringen.no/no/dokumenter/nyere-kunnskap-om-inkluderende-arbeidsliv-ia/id2628425/


[hyttepaaske]: https://www.nrk.no/ytring/hyttepaske-for-hvem_-1.15418469
[krise]: https://www.aftenposten.no/meninger/kronikk/i/50gQGb/maa-det-en-krise-til-foer-politikerne-vaakner-jon-h-fiva-og-oda-nedregaard
[amerikanske_tilstander]: https://www.dagsavisen.no/debatt/2019/12/10/amerikanske-tilstander/
[faglig_interessert]: https://forskning.no/oslomet-skole-og-utdanning-partner/faglig-interesserte-studenter-fullforer-oftere-utdanningen/1231170
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```
